
export const keybindingActions: { [key: string]: string } = {
    FinishLine: "完成字幕",
    EditLine: "開始修改字幕",
    DeleteLine: "刪除所選字幕",
    Play: "播放媒體",
    Pause: "暫停媒體",
    PlayPeriod: "播放字幕區間",
    Split: "分割字幕",
    Marge: "合併所選字幕",
    MargePrev: "與前一句合併",
    MargeNext: "與後一句合併",
    EditPrev: "編輯前一句",
    EditNext: "編輯後一句",
    SelectPrev: "選擇前一句",
    SelectNext: "選擇後一句",
    AddSelectPrev: "增加選擇前一句",
    AddSelectNext: "增加選擇後一句",
    InsertBefore: "在本句前插入一句",
    InsertAfter: "在本句後插入一句",
    SelectAll: "全選",
    Search: "搜尋",
    ShiftTime: "推移時間",
    RecoverToOriginal: "還原回原始資料",
    Undo: "上一步",
    Redo: "下一步",
    Save: "快速儲存",
    QuickCreateLine: "從逐字稿快速建立新行",
    PrevSecond: "播放器回推一秒",
    NextSecond: "播放器前進一秒"
};