import { Api } from "uform-api";

export const topicApiMap = {
    get: <Api>{ url: "/Topic/Get", method: "GET" },
    getListItem: <Api>{ url: "/Topic/GetListItem", method: "GET" },
    getSubtitle: <Api>{ url: "/Topic/GetSubtitle", method: "GET" },
    getAsrAccess: <Api>{ url: "/Topic/GetAsrAccess", method: "Get" },
    list: <Api>{ url: "/Topic/ListTopic", method: "GET" },
    create: <Api>{ url: "/Topic/Create", method: "POST" },
    update: <Api>{ url: "/Topic/Update", method: "POST" },
    updateWordLimit: <Api>{ url: "/Topic/UpdateWordLimit", method: "POST" },
    updateSubtitle: <Api>{ url: "/Topic/UpdateSubtitle", method: "POST" },
    updateUpdateTranscript: <Api>{ url: "/Topic/UpdateTranscript", method: "POST" },
    pause: <Api>{ url: "/Topic/Pause", method: "POST" },
    resume: <Api>{ url: "/Topic/Resume", method: "POST" },
    archive: <Api>{ url: "/Topic/Archive", method: "POST" },
    batchArchive: <Api>{ url: "/Topic/BatchArchive", method: "POST" },
    reExecute: <Api>{ url: "/Topic/ReExecute", method: "POST" },
    remove: <Api>{ url: "/Topic/Remove", method: "POST" },
    setNormal: <Api>{ url: "/Topic/SetNormal", method: "POST" },
    batchRemove: <Api>{ url: "/Topic/BatchRemove", method: "POST" },
    reuploadSubtitle: <Api>{ url: "/Topic/ReuploadSubtitle", method: "POST" },
    reuploadTranscript: <Api>{ url: "/Topic/ReuploadTranscript", method: "POST" },
    reproduceSubtitle: <Api>{ url: "/Topic/ReproduceSubtitle", method: "POST" },
    reloadSubtitle: <Api>{ url: "/Topic/ReloadSubtitle", method: "POST" },
    recoverToOriginal: <Api>{ url: "/Topic/RecoverToOriginal", method: "POST" },
    exportSubtitle: <Api>{ url: "/Topic/ExportSubtitle", method: "GET" },
    exportTranscript: <Api>{ url: "/Topic/ExportTranscript", method: "GET" },
    downloadRawFile: <Api>{ url: "/Topic/DownloadRawFile", method: "GET" },
    doTopicConversionBenchmark: <Api>{ url: "/Topic/DoTopicConversionBenchmark", method: "POST" },
};